-- SQLite

/**
    Will include all 413 rows from the Invoice table
    Matches all records in both tables where the customer id is the same
    If there's a customer ID associated with a particular InvoiceID that doesn't exist in the customer table, then in the resulting table, the invoiceID is copied as is but a NULL is inserted in the CustomerID slot
*/

SELECT
    c.LastName,
    c.FirstName,
    i.InvoiceId,
    i.CustomerId,
    i.InvoiceDate,
    i.Total
FROM
    Invoice as i
LEFT OUTER JOIN
    -- the left table here is Invoice and right table is Customer
    -- all the rows from the Invoice table are included along with the intersection between records in both the tables
    Customer as c
ON
    i.CustomerId = c.CustomerId
ORDER BY
    -- once again done to view the invoices generated by each customer
    c.CustomerId